---
- block: # Check and register for fluentd configuration file

  - name: Set list of path to look for fluentd configuration file
    set_fact:
      automated_docker_fluentd_config_file_paths: "{{ automated_docker_fluentd_config_file_paths }} + [ '{{ automated_docker_fluentd_config_file_path }}' ]"
    with_items: "{{ group_names }}"

  - name: Check if fluentd configuration file is exists
    stat:
      path: "{{ item }}"
    register: automated_docker_fluentd_config_check
    with_first_found:
      - files: "{{ automated_docker_fluentd_config_file_paths }}"
        skip: true
  - name: Set fluentd configuration file path
    set_fact:
      automated_docker_fluentd_config_stat: "{{ automated_docker_fluentd_config_check.results[0].stat }}"
    when: automated_docker_fluentd_config_check.results[0].stat is defined


- block: # Copy all configuration files to fluentd container

  # TODO Still need to delete and recreate directory again until
  # empty tag is coming here
  # https://github.com/ansible/ansible-modules-core/issues/902
  - name: Delete fluentd configuration backup directory
    file:
      path: "{{ automated_docker_fluentd_config_backup_path }}"
      state: absent
    delegate_to: "{{ automated_docker_run.name }}"
    when: |
      automated_docker_fluentd_config_stat is defined and
      automated_docker_fluentd_config_stat.exists == true
  - name: Check if there is old configuration file in the fluentd configuration path
    stat:
      path: "{{ automated_docker_fluentd_config_path }}/*.conf"
    register: automated_docker_fluentd_config_path_check
  - name: Create fluentd configuration backup directory
    file:
      path: "{{ automated_docker_fluentd_config_backup_path }}"
      state: directory
    delegate_to: "{{ automated_docker_run.name }}"
    when: |
      automated_docker_fluentd_config_stat is defined and
      automated_docker_fluentd_config_stat.exists == true and
      automated_docker_fluentd_config_path_check.results[0].stat.exists

  # Need to use shell because command module doesn't support delegate_to
  # docker container
  - name: Backup current fluentd configuration file
    shell: "mv {{ automated_docker_fluentd_config_path }}/* {{ automated_docker_fluentd_config_backup_path }}/"
    delegate_to: "{{ automated_docker_run.name }}"
    when: |
      automated_docker_fluentd_config_stat is defined and
      automated_docker_fluentd_config_stat.exists == true and
      automated_docker_fluentd_config_path_check.results[0].stat.exists

  # Need to use docker cp because copy module does not support copy symlink file
  - name: Copy new fluentd configuration file
    command: |
      docker cp "{{ automated_docker_fluentd_config_stat.path | dirname }}/." \
      "{{ automated_docker_run.name }}":"{{ automated_docker_fluentd_config_path }}"
    when: |
      automated_docker_fluentd_config_stat is defined and
      automated_docker_fluentd_config_stat.exists == true
    environment: "{{ automated_docker_machine_environment | default({}) }}"
    notify: Restart container
    # notify: Check fluentd configuration and reload fluentd

  # TODO Backup and revert if check fluentd configuration not passes
